### ISSUE TITLE
实现了直连p站但是不能连e站的问题

### ISSUE THREAD

**Issue by jtenu** [rabbit2123/domain-fronting#2]
每次pixiv都是秒开，e站就是502 bad gateway，ip地址也都没有搞错，望解答

**Comment by rabbit2123** [comment]
哪一个e站

**Comment by jtenu** [comment]
> 哪一个e站

e-hentai.org

**Comment by rabbit2123** [comment]
这网站不支持域前置，要用cloudflare workers/pages转发才行。
