### ISSUE TITLE
试了第一种方法，wiki能打开了，但google，openai等还是打不开，求指教

### ISSUE THREAD

**Issue by immorrrtal** [rabbit2123/domain-fronting#4]

**Comment by rabbit2123** [comment]
修复Google了，openai只能用api，chat.openai.com是打不开的

**Comment by immorrrtal** [comment]
成功了，非常感谢！！

**Comment by immorrrtal** [comment]
另外想问下YouTube能打开但播放不了视频，有办法解决吗

**Comment by rabbit2123** [comment]
播放youtube视频只能用cloudflare workers/pages转发。

另外如果想用chatgpt，试试这两个，用邮箱注册就行。
https://poe.com/ChatGPT
https://chat.forefront.ai/

**Comment by immorrrtal** [comment]
ok 感谢

**Comment by rikka0w0** [comment]
`curl https://www.gstatic.cn:45030/ -H "Host: www.google.com" --resolve www.gstatic.cn:45030:183.91.243.26 -v`

用curl工具（Linux，WSL，MAC）可以测试能不能域名前置访问google

**Comment by rikka0w0** [comment]
Youtube视频源的ip其实是可以直连的，虽然会被SNI屏蔽，但是采用域名前置是可以访问的：
`curl -6kv --resolve qwq.com:443:[2404:6800:4004:2b::a] -H "Host: rr5---sn-oguelnzs.googlevideo.com" https://qwq.com`

不知道能否加入规则
